# name: Deploy to Cloud Run (WITH GPU)

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# env:
#   GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
#   REGION: "us-central1"
#   SERVICE_NAME: whisper-translate-gpu

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Google Auth
#         id: auth
#         uses: 'google-github-actions/auth@v2'
#         with:
#           credentials_json: ${{ secrets.GCP_CREDENTIALS }}

#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ env.GCP_PROJECT_ID }}
#           install_components: beta
      
#       - name: Who am I?
#         run: |
#           service_account=$(gcloud config get-value account)
#           echo "Active Service Account: $service_account"

#       - name: Authenticate Docker with Google Container Registry
#         run: gcloud auth configure-docker

#       - name: Build Docker Image
#         run: |
#           docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} -f Dockerfile .

#       - name: Push Docker Image
#         run: |
#           docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

#       - name: Deploy to Cloud Run (WITH GPU)
#         run: |
#           gcloud beta run deploy ${{ env.SERVICE_NAME }} \
#             --image gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
#             --region ${{ env.REGION }} \
#             --cpu 4 \
#             --memory 16Gi \
#             --timeout 60 \
#             --gpu 1 \
#             --gpu-type nvidia-l4 \
#             --max-instances 1 \
#             --quiet
name: Build Docker Image on Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: beta

      - name: Authenticate Docker with Google Container Registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/kokila-v0/github:latest .
          # docker build -t asia-southeast1-docker.pkg.dev/stage-agni/kokila-v0:latest -f Dockerfile .
                    
      - name: Push Docker image
        run: |
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/kokila-v0/github:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy kokila \
              --image asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/kokila-v0/github:latest \
              --region asia-southeast1 \
              --allow-unauthenticated \
              --memory 16Gi \
              --cpu 4 \
              --timeout 900
